export default {
    ADD_COMMAND: 'ADD_COMMAND',
    EXEC_COMMAND: 'EXEC_COMMAND',
    OUTPUT_COMMAND: 'OUTPUT_COMMAND',
    HISTORY_INCREMENT: 'HISTORY_INCREMENT',
    HISTORY_DECREMENT: 'HISTORY_DECREMENT',
};
